# Generated by Django 4.2.11 on 2024-03-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('TECHNICIAN', 'Technician'), ('MASTER', 'Master'), ('WORKER', 'Worker')], default='CUSTOMER', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='email address'),
        ),
    ]
